server:
  port: 8080
  servlet:
    context-path: /
#  ssl:
#    enabled: true
#    ciphers: TLS_RSA_WITH_AES_128_CBC_SHA256
#    protocol: TLS
#    enabled-protocols: TLSv1.2
#    key-store: /Users/yuhan/keystore/kstore.keystore
#    key-store-password: init234
#    key-store-type: JKS
spring:
  profile: prod
  application:
    name: mySpringbootDemo
  datasource:
    db1:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mytest
      username: root
      password: root
    db2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/slavetest
      username: root
      password: root
      enabled: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 5
      maximumPoolSize: 50
      maxLifetime: 180000
      idleTimeout: 60000
      connectionTimeout: 20000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    ssl: false
    timeout: 5000
    password: 123
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mytest
#    username: root
#    password: root
#  hikari:
#    maximum-pool-size: 2
#    minimun-idle: 1
#    max-lifetime: 60000
#    connection-timeout: 500
#    login-timeout: 500
#    validation-timeout: 1000
#    initialization-fail-timeout: 1000
#    idleTimeout: 60000
  management:
    endpoints:
      web:
        exposure:
          include: mappings,info,health
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example.demo.common.model
#  configuration:
#    cache-enabled: false
#    local-cache-scope: statement
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
sentinel:
  dashboard:
    server: localhost:9090


